server:
    port: 80
    contextPath:

spring:
    profiles:
        active: dev

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/spring_blog?serverTimezone=UTC
      username: root
      password: peli

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

